### PR TITLE
Added top contributor snippet at the top

### PR DESCRIPTION
**Pull request by captainbrosset**
This adds the names and bug numbers of the top contributors over the last 30 days.
Clicking the name opens the corresponding bugzilla profile (based on the name we get from bugzilla which, oddly, doesn't always works), clicking on the number of bugs opens the list of bugs in bugzilla.
The list is sorted by nb of bugs fixed.
Only people with more than 1 fix are displayed.
DevTools staff members are filtered out.

capture

### CODE REVIEW

**Comment by captainbrosset** [comment]
@nt1m @nchevobbe @jsnajdr: what do you think?
I'm pinging you because you end up on this list the most often, so I'd like your point of view about this :)

**Comment by nchevobbe** [comment]
Looks cool to me !
Could it be more inclusive though ? Instead of only getting the top contributors, maybe it could display all the contributors of the month ? Something like : 

20 people contributed to the devtools last month : Jarda (12), mkohler(8), nchevobbe (6), yzen (4)... [\+ See the complete list](url)

So everyone who contributed can gets credit ?

**Comment by nchevobbe** [comment]
Or maybe even better, display : "45 bugs were fixed by contributors last month : Jarda(12) ..."

**Comment by nt1m** [comment]
Looks nice! I like Nicolas' suggestion. Also, just looked at the code, and maybe it would be easier to simply filter out people with mozilla.com emails (and blacklist team members with a custom email) ?

**Comment by captainbrosset** [comment]
> Or maybe even better, display : "45 bugs were fixed by contributors last month : Jarda(12) ..."

@nchevobbe good idea. I'll push some changes soon.

> Also, just looked at the code, and maybe it would be easier to simply filter out people with mozilla.com emails

@nt1m That's what I wanted to do but I couldn't figure out a way to retrieve email addresses from the bugzilla API. Documentation is scarce. I think there might be a way to do it if I first retrieve the bugs and then do one more call per bug to retrieve assignee info. But that will be way too slow. The API is pretty slow as it is, and I'd like to be able to get all the info I need in one call only.

**Comment by jsnajdr** [comment]
Looks nice, thanks for asking!

**Pull request merged**
