### PR TITLE
Add DOM component

### PR DESCRIPTION
**Pull request by jryans**

### CODE REVIEW

**Comment by nt1m** [comment]
You might want to remove the 3D view component while you're there: https://github.com/jryans/devtools-bug-finder/blob/add-dom/app.js#L80

**Comment by nt1m** [comment]
@jryans The new component needs its own colour here too: https://github.com/captainbrosset/devtools-bug-finder/blob/gh-pages/style.css#L75

**Comment by jryans** [comment]
Thanks! I think I've addressed @nt1m's comments.

**Comment by nt1m** [comment]
Thanks, merged !

**Pull request merged**
