### PR TITLE
Footer always bottom.

### PR DESCRIPTION
**Pull request by StefanYohansson**
137.2px = 
42.6 * 2 (header and footer height) + 50 (main margin top and bottom) + 2 (header and footer border)

Before:

2017-03-01-142332_2048x1920_scrot

After:

2017-03-01-142558_2048x1920_scrot

### CODE REVIEW

**Comment by nt1m** [comment]
Thanks for the PR! I think a better fix would be adding height: 100% [here](https://github.com/captainbrosset/devtools-bug-finder/blob/gh-pages/style.css#L4). There seems to be code that implements a flex layout that's supposed to do this, but it seems to be missing the height: 100%;

**Comment by StefanYohansson** [comment]
@nt1m Thanks. I'll update it asap.

**Comment by StefanYohansson** [comment]
@nt1m updated.

**Comment by nt1m** [comment]
Thanks!

**Pull request merged**
